# 线上配置文件

spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-lqdvuvo8.sql.tencentcdb.com:26167/zhihe
    username: root
    password: Yangyang0807
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0